apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: observability-labs

resources:
  - namespace.yaml
  - postgres.yaml
  - redis.yaml
  - app.yaml

secretGenerator:
  - name: postgres-secrets
    literals:
      - POSTGRES_DB=orders
      - POSTGRES_USER=orders_app
      - POSTGRES_PASSWORD=orders_app_lab_password
  - name: app-secrets
    literals:
      - APP_DATABASE_URL=postgresql+asyncpg://orders_app:orders_app_lab_password@db:5432/orders

generatorOptions:
  disableNameSuffixHash: true
